version: '3'

services:
  app:
    build: .
    container_name: fast-app
    network_mode: host
    ports:
      - "8000:000"
    # command: bash -c "uvicorn main:app"
    env_file:
      - .env
